include: package:very_good_analysis/analysis_options.5.1.0.yaml

analyzer:
  exclude:
    - "**/*.g.dart"

  plugins:
    - custom_lint

linter:
  rules:
    sort_pub_dependencies: false
    public_member_api_docs: false
    prefer_const_constructors: false
    avoid_renaming_method_parameters: false
